name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Замени на свою основную ветку, если не main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Или версия, которую ты используешь

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # Ветка для деплоя
          folder: dist      # Директория сビルдом (для Vite это dist)